### ISSUE TITLE
Cannot run ALS algorithm with oap-mllib thanks to the commit "2883d3447d07feb55bf5d4fee8225d74b0b1e2b1"

### ISSUE THREAD

**Issue by haojinIntel** [oap-project/oap-mllib#116]
Thanks to the commit "2883d3447d07feb55bf5d4fee8225d74b0b1e2b1" of branch-1.2, running ALS with oap-mllib encounter the following issue:
```
2021-08-11 10:58:40,941 ERROR scheduler.TaskSetManager: Task 2 in stage 7.0 failed 4 times; aborting job
2021-08-11 10:58:40,949 INFO cluster.YarnScheduler: Cancelling stage 7
2021-08-11 10:58:40,949 INFO cluster.YarnScheduler: Killing all running tasks in stage 7: Stage cancelled
2021-08-11 10:58:40,958 INFO cluster.YarnScheduler: Stage 7 was cancelled
2021-08-11 10:58:40,959 INFO scheduler.DAGScheduler: ResultStage 7 (collect at Utils.scala:102) failed in 12.733 s due to Job aborted due to stage failure: Task 2 in stage 7.0 failed 4 times, most recent failure: Lost task 2.3 in stage 7.0 (TID 638) (bdpe-sky3 executor 9): java.lang.UnsatisfiedLinkError: org.apache.spark.ml.util.OneCCL$.c_getAvailPort(Ljava/lang/String;)I
        at org.apache.spark.ml.util.OneCCL$.c_getAvailPort(Native Method)
        at org.apache.spark.ml.util.OneCCL$.getAvailPort(OneCCL.scala:54)
        at org.apache.spark.ml.util.Utils$.$anonfun$checkExecutorAvailPort$1(Utils.scala:103)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
2021-08-11 10:58:40,961 INFO scheduler.DAGScheduler: Job 6 failed: collect at Utils.scala:102, took 27.956369 s
2021-08-11 10:58:40,964 ERROR util.Instrumentation: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 7.0 failed 4 times, most recent failure: Lost task 2.3 in stage 7.0 (TID 638) (bdpe-sky3 executor 9): java.lang.UnsatisfiedLinkError: org.apache.spark.ml.util.OneCCL$.c_getAvailPort(Ljava/lang/String;)I
        at org.apache.spark.ml.util.OneCCL$.c_getAvailPort(Native Method)
        at org.apache.spark.ml.util.OneCCL$.getAvailPort(OneCCL.scala:54)
        at org.apache.spark.ml.util.Utils$.$anonfun$checkExecutorAvailPort$1(Utils.scala:103)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by haojinIntel** [comment]
@xwu99 @zhixingheyi-tian Please help to track the issue. Thanks!
